name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *" # تشغيل كل 24 ساعة
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Madyelshshaht

      - name: Move generated file to dist
        run: |
          mkdir dist
          mv pacman-contribution-graph.svg dist/

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
